typography_spectrum: 0.7539528997149318
color:
  brandStrength: 0.7810077907051891
  lightness: 0.743061215383932
  saturation: 0.5370947127230465
  rhythmicContrast: 0.011343022575601935
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.09444149606861174
name: Kristian Wind Fotografi
title: Bryllupsfotograf
